name: Sync Fork Nightly
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync_fork_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          base: nightly
          head: nightly
          retries: 1
          retry_after: 10
          ignore_fail: true
          token: ${{ secrets.GITHUB_TOKEN }}
