name: Sync Fork Master
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync_fork_master:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          base: master
          head: master
          retries: 1
          retry_after: 10
          ignore_fail: true
          token: ${{ secrets.GITHUB_TOKEN }}
